package com.epam.jwd.entity.enums;

public enum Brand {
    AEG, THOMAS, ELECTROLUX, BRAUN, KARCHER, ROWENTA, KAISER,
    INDESIT, DELONGHI, TEFAL, MOULINEX, BEKO, SAMSUNG, LG,
    DAEWOO, TOSHIBA, HITACHI, PANASONIC, SONY, KENWOOD, DAIKIN,
    BOSCH, MITSUBISHI, ATLANT, HORIZONT, MIDEA, SCARLET, REDMOND,
    XIAOMI, DEERMA, PHILIPS, HAIER

}
